DATA := $(shell find data -type f)
DB := {{slug}}.db

.DEFAULT_GOAL := dist

$(DB):

%.gz: $(DB)
	gzip --force --keep $< >$@

SHA256SUMS: $(DB).gz
	sha256sum *.gz >$@

.PHONY: clean
clean:
	$(RM) -r $(DB) dist/

.PHONY: dist
dist:
	mkdir -p dist
	make dist/$(DB).gz
	cd dist && sha256sum *.gz >SHA256SUMS

.PHONY: fetch
fetch:
